Basic ping fix MATHNET-5
build3/MathNetClient pull request #3
Opened 2019-06-11 13:20 UTC by Polej

2019-06-11 15:21 UTC, KamilSupera commented on codap_plugin.html
> +                        <h5 class = "ping"> Ping : waiting </h5>
Too many spaces.

2019-06-11 15:24 UTC, KamilSupera commented on codap_plugin.html
> +
Unneeded line.

2019-06-12 08:07 UTC, BarryOgg requested changes

2019-06-12 08:07 UTC, BarryOgg commented on admin.html
> +          <h5 class = "ping"> Ping : waiting </h5>
There shouldn't be spaces around the '=' in html attributes. Please also fix that in lines that haven't been modified by you (e.g. 141 and 142).

2019-06-12 08:07 UTC, BarryOgg commented on admin.html
> +                <input type="text" class="form-control class_input" id="class_input" name="class_input" required="" placeholder="Class Name"/>
`required` doesn't need to have a value.

2019-06-12 08:07 UTC, BarryOgg commented on admin.html
> +                <input type="text" class="form-control class_input" id="class_input" name="class_input" required="" placeholder="Class Name"/>
The usual convention for class names is kebab-case, and even if there's a different case used, they shouldn't be  mixed, especially not in a single element, like snake_case here. And for that matter, the usual convention for `id` is camelCase.

Unlike the spaces around `=`, you don't need to fix this in the whole file right now, as it'd require more work than find&replace. Just try and fix in the part you'll be working on.

2019-06-12 08:07 UTC, BarryOgg commented on admin.html
> +          <p class="error error_password_mismatch" hidden> Passwords do not match <br/> </p>
If text content of a node is in a single line, there shouldn't be spaces around it.

2019-06-12 08:07 UTC, BarryOgg commented on src/Admin.js
> +        socket.on('ping_mathnet-response', (time) => {
Like in class names, you shouldn't mix two types of case in one identifier.

2019-06-12 09:50 UTC, BarryOgg requested changes

2019-06-12 09:50 UTC, BarryOgg commented on admin.html
> +                <input id = "delete_class_button" class="btn btn-danger delete_class_button" type="button" value="Delete Class">
There are still spaces around `=`

2019-06-12 09:50 UTC, BarryOgg commented on admin.html
> +                <input type="text" class="form-control class_input" id="class_input" name="class_input" placeholder="Class Name"/>
By "required doesn't need to have a value", I meant that you can have just an attribute, i.e. just `required` instead of `required=""`

2019-06-12 09:50 UTC, BarryOgg commented on admin.html
> +          <h5 class = "ping">Ping : waiting</h5>
There are still spaces around `=`

2019-06-12 09:50 UTC, BarryOgg commented on admin.html
> +                    <p id = "hello">Select Construction</p>
Ditto (spaces around `=`)

2019-06-12 09:50 UTC, BarryOgg commented on admin.html
> +                    <p id = "hello">Select Default ToolBar</p>
Extra spaces

2019-06-12 09:50 UTC, BarryOgg commented on admin.html
> +          <h5 class = "ping"> Ping : waiting </h5>
Extra spaces, I suggest find & replace on ' = "'

2019-06-12 09:50 UTC, BarryOgg commented on admin.html
> +          <h5 class = "ping"> Ping : waiting </h5>
(7 instances of extra spaces below, I'm not gonna comment on each)

2019-06-12 09:54 UTC, BarryOgg commented on admin.html
> +                <input type="text" class="form-control class_input" id="class_input" name="class_input" placeholder="Class Name"/>
Oh, and there are still spaces around text in a single-line `<p>` below this line.

2019-06-13 09:50 UTC, BarryOgg approved these changes

2019-06-13 09:51 UTC, merged